laplace-ensemble:
  # --- File Paths & Basic Model Details ---
  la_sampled_models_dir: "/dtu/blackhole/13/213811/s243425/gaussian_experiment/models/la_sampled"
  last_layer_name: "out_fc" # Only used if subset='last_layer'
  
  # Essential for accuracy: How much data you use to compute the Hessian matrix. 
  # Higher = better approximation, but takes longer and uses more memory. 64x2048 is a good robust default.
  laplace_batches: 64
  laplace_batch_size: 2048

  # Regularization params
  # Essential: Acts as the `lambda` in (H + \lambda I)^-1. High values (e.g., 10.0) 
  # strictly prevent the model from collapsing to noise by regularizing flat directions in the loss landscape.
  prior_precision: 0.1 
  # Simplification: With proper prior_precision, you can just leave this at 1.0 (no effect).
  sample_temperature: 0.01 # Higher values (e.g., 2.0) increase the diversity of sampled models but can lead to worse performance if set too high. 
  
  approximation: "icla" # 'full' (full Hessian) is the most accurate but computationally expensive. 'diagonal' is a scalable approximation.
  curvature: "ef" # 'ggn' (Generalized Gauss-Newton) or 'ef' (Empirical Fisher).
  # Essential: 'last_layer' is safer but less expressive. 'random' is more expressive but requires tuning the regularizers above.
  subset: "last_layer" # 'last_layer' or 'random'
  m: 16384 # if subset='random', how many parameters to capture. 3000 is a sweet spot. Too low = no uncertainty diversity. Too high = requires extreme prior_precision to remain stable.
  
  # Reproducibility & Downstream Tasks ---
  weight_sampling_seed: 42
  subset_seed: 42        

lora-ensemble:
  lora_sampled_models_dir: "/dtu/blackhole/13/213811/s243425/gaussian_experiment/models/lora_sampled"
  M: 5
  r: 4
  alpha: 2.0 # 4.0
  epochs: 20 
  lr: 0.001
  batch_size: 2048

# was trained with Aithal et al. original code
deep-ensemble:
  # trained_models_dir: "chkpts/gaussian25_100000_g_1_e_10000_t1000_m128_nl3_blinear_seed{seed}_s1_fds_ensemble_model_seed_{seed}"
  trained_models_dir: "chkpts/gaussian25_100000_g_1_e_10000_t1000_m128_nl3_blinear_seed{seed}_fixed_ds_ensemble_model_seed_{seed}" 
  sel_generation: 0
  M: 5

sampling:
  num_samples: 65536
  batch_size: 8192
  samples_cache_dir: "/dtu/blackhole/13/213811/s243425/gaussian_experiment/samples"